spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_spring_next?serverTimezone=Asia/Seoul
    username: blogadmin
    password: blogadmin