name: next-blog deploy
on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest source
        uses: actions/checkout@v4
        
      - name: Set env
        run: |
          touch ./.env.local
          echo "${{ secrets.NODE_ENV }}" > ./next/.env.local
        shell: bash

      - name: Login dockerHub
        run: |
          echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USER }}/next-blog ./next 
          docker push ${{ secrets.DOCKER_USER }}/next-blog:latest
      
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
            touch /BLOG/next/.env.local
            echo "${{ secrets.NODE_ENV }}" > /BLOG/next/.env.local
            docker compose down || true
            docker image prune -f
            docker pull ${{ secrets.DOCKER_USER }}/next-blog:latest
            docker compose up -d